// auto-generated by ./scripts/hydrate.sh
export function filter<T>(callback: (item: T) => boolean, array: T[]): T[] {
	const result: T[] = [];
	for (const item of array) {
		if (callback(item)) {
			result.push(item);
		}
	}
	return result;
}
