import type { Metadata } from "next";
import { Roboto, Roboto_Mono, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const robotoSans = Roboto({
	variable: "--font-roboto-sans",
	subsets: ["latin"],
	weight: ["100", "300", "400", "500", "700", "900"],
});

const robotoMono = Roboto_Mono({
	variable: "--font-roboto-mono",
	subsets: ["latin"],
});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={[
					robotoSans.variable,
					robotoMono.variable,
					// geistSans.variable,
					// geistMono.variable,
					"antialiased",
				].join(" ")}
			>
				{children}
			</body>
		</html>
	);
}
