// auto-generated by ./scripts/hydrate.sh
const assert = require("node:assert");

const packages = [
	require("@level-ones/tsc-bundler"),
	require("@level-ones/tsc-node10"),
	require("@level-ones/tsc-node16"),
	require("@level-ones/esbuild-bundler"),
	require("@level-ones/esbuild-node10"),
	require("@level-ones/esbuild-node16"),
];

for (const pkg of packages) {
	assert.strictEqual(typeof pkg.default, "string");

	assert.deepStrictEqual(
		pkg.filter((x) => x % 2 === 0, [1, 2, 3, 4, 5]),
		[2, 4],
	);

	assert.deepStrictEqual(
		pkg.map((x) => x * 2, [1, 2, 3, 4, 5]),
		[2, 4, 6, 8, 10],
	);
}
