/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number;
export declare class RustModuleReferenceChanger {
	static create(): RustModuleReferenceChanger;
	changeReferencesInDir(mjsdir: string): void;
}
export declare class RustExtensionChanger {
	static create(): RustExtensionChanger;
	changeInDir(dir: string, fromExtension: string, toExtension: string): void;
}
export declare class RustFsFilesRepository {
	static create(): RustFsFilesRepository;
	getPackageDir(): string;
	isDir(uri: string): boolean;
	mv(fromUri: string, toUri: string): void;
	remove(uri: string): void;
	children(uri: string): Array<string>;
	read(uri: string): string;
	write(uri: string, content: string): void;
}
