[package]
name = "zoboz-bam"
version = "1.3.1"
edition = "2024"

[dependencies]
oxc_resolver = "5.0.0"
regex = "1"
lazy_static = "1"
serde = "1"
serde_json = { version = "1", features = ["preserve_order"] }
shell-words = "1"

[dev-dependencies]
tempfile = "3"
cucumber = "0.21"
futures = "0.3"

[[test]]
name = "definitions"
harness = false      # allows Cucumber to print output instead of libtest
